app:
  name: Sample App
  url: http://localhost:8080/

## Set the dependencies the way you want,
## You will have to define your dependency container in Dependencies.php
## and use the data you set here to call the dependencies there
dependencies:
  ## example =>
  ## Core\Interface\TemplateRendererInterface:
  ##    class: \App\Service\TwigRenderer
  ## homeController:
  ##    class: \App\Controller\HomeController
  ##    arguments:
  ##        Core\Interface\TemplateRendererInterface
